# -*- coding: utf-8 -*-
"""Vaishnavi.V

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfrPGWH3H6jgi7rE7rKQdDT93MGedy3u
"""

Indro=("I am signing up for Replit's 100 days of Python challenge! I will make sure to spendsome time every day coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.No excuses for not coding from the middle of a field!")
print(Indro)

malware={'virus':'DDoS attacks','malveristing':'Steal data','worms':'human interaction','rootkits':' hijack'}
print(malware)
print(malware.values())
print(malware.items())
print(malware.keys())
print(malware.clear())

print("\Calculating GST and Net price")
#op=orginal price
#p=gst persentage
#NA=net amount
op =12300
p=18
GST=(op*p)/100
print ("GST:Rs.",GST)
NA =(op+GST)
print("Net price:Rs.",NA)

import pandas as pd
df=pd.DataFrame ({
                  'offence':['sending threatning messages by email','sending defamatory messages by email','forgery or electronic records','bogus website cyber frauds','email spoofing','web jacking','email abuse','online sale of drugs','online sale of arms'],
                   'law':['sec 503 ipc','sec 499 IPC','sec 463 IPC','sec 420 ipc','sec 463 IPC','sec 383 IPC','sec 500 IPC','NDPS','arms act']})
print(df)

import pandas as pd
data = {
"name": ['vaish', 'kesu', 'dharani', 'moni', 'sheba', 'sherin', 'monika', 'sangeetha', 'rangani', 'sindhu'],
"date": [2002, 2002, 2002, 2003, 2000, 2009, 2002, 2004, 2003, 2005,],
"weigh": ['65kg', '50kg', '55kg', '45kg', '80kg', '35kg', '30kg', '20kg', '40kg', '40kg',],
"height": ['120cm', '100cm', '180cm', '160cm', '190cm', '180cm', '160cm', '130cm', '175cm', '165cm',]
}
df=pd.DataFrame(data)
df['age']=2022-df['date']
df['health status']=df['age'].apply (lambda X:'critical' if X>58 else 'normal')
print (df)

def household():
  print("\CALCULATING HOUSEHOLD EB PRICE")
  unit=int(input("\nNUMBER OF UNITS USED: "))

  if unit<100:
    price=unit*0.50
    print("YOUR PRICE : Rs.",price)
  elif unit>101 and unit<200:
    price=unit*0.75
    print("YOUR PRICE : Rs.",price)
  elif unit>201 and unit<300:
    price=unit*1.20
    print("YOUR PRICE: Rs.",price)
  else:
    price=unit*1.50
    print("YOUR PRICE : Rs.",price)

household()