# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKv8USuTn62IP14K4-J01xBslgsodgAr
"""

DT_A = 22
DT_A
print(DT_A)
type(DT_A)



dt_str="cyber security"
type(dt_str)

A=7.0
B=13
C= A+B
print(C)
type (C)

a='37'
b='vaishu'
a+b

a='help me god '
print(a)
a.upper()

my_string='i dont know'
my_string.upper()
my_string.lower()
my_string.find ('o')
my_string.replace('i','k')

float(DT_A)
A=55.2
int(A)

(77/99)*2+3

160/60

animals=['dog', 'cat','parrrot','cow']
print(animals)
animals=[3,3.0,22,'b+c']
print(animals)
print(len(animals))
print(animals[3])
print(animals[0:4])
animals.extend('v')
print(animals)
animals.append('k')
print(animals)

name=('bheem','chutki','raju','jacku','kaliya','dolu','polu')
bloodgroup =('A','B','O','AB+','AB-','O-','B-')
name + bloodgroup



vaishu =(1,2,('vv','kv'),(13,13),('cby',(1,2)))
print(vaishu[2])
print(vaishu[2][1])
print(vaishu[-2])
print(vaishu[2][1][1])

chootabheem={'hero':'bheem','heroeni':'chutki','friend':'raju','co-friend':'jaku','villan':'kirmada'}
print(chootabheem)
print(chootabheem.keys())
print(chootabheem.values())
print(chootabheem['villan'])
del(chootabheem['villan'])
print(chootabheem)
chootabheem['place']='dollakpoor'
print(chootabheem)